### ISSUE TITLE
simengine does not run on Centos 8

### ISSUE THREAD

**Issue by fabbione** [Seneca-CDOT/simengine#156]
After working around the rpm install issues reported in #155:

# rpm -qa |grep simen
simengine-dashboard-3.37-1.el8.x86_64
simengine-core-3.37-1.el8.x86_64
simengine-database-3.37-1.el8.noarch

Both redis and neo4j are running fine (according to systemctl).

Running simengine-core fails with python traceback:

# systemctl status simengine-core
● simengine-core.service - SimEngine Core Daemon
   Loaded: loaded (/usr/lib/systemd/system/simengine-core.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2021-08-14 00:22:51 EDT; 13s ago
  Process: 3389848 ExecStart=/usr/share/simengine/enginecore/app.py (code=exited, status=1/FAILURE)
 Main PID: 3389848 (code=exited, status=1/FAILURE)

# /usr/share/simengine/enginecore/app.py
Traceback (most recent call last):
  File "/usr/share/simengine/enginecore/app.py", line 12, in <module>
    from enginecore.state.redis_state_listener import StateListener
  File "/usr/share/simengine/enginecore/enginecore/state/redis_state_listener.py", line 12, in <module>
    from enginecore.state.redis_state_handler import RedisStateHandler
  File "/usr/share/simengine/enginecore/enginecore/state/redis_state_handler.py", line 13, in <module>
    from enginecore.state.net.ws_server import WebSocket
  File "/usr/share/simengine/enginecore/enginecore/state/net/ws_server.py", line 12, in <module>
    from enginecore.state.api import IStateManager, ISystemEnvironment
  File "/usr/share/simengine/enginecore/enginecore/state/api/__init__.py", line 6, in <module>
    from enginecore.state.api.server import (
  File "/usr/share/simengine/enginecore/enginecore/state/api/server.py", line 9, in <module>
    import enginecore.model.system_modeler as sys_modeler
  File "/usr/share/simengine/enginecore/enginecore/model/system_modeler.py", line 16, in <module>
    GRAPH_REF = GraphReference()
  File "/usr/share/simengine/enginecore/enginecore/model/graph_reference.py", line 26, in __init__
    os.environ.get("NEO4J_PSW", "simengine"),
  File "/usr/lib64/python3.6/site-packages/neo4j/v1/api.py", line 94, in driver
    return Driver(uri, **config)
  File "/usr/lib64/python3.6/site-packages/neo4j/v1/api.py", line 133, in __new__
    return subclass(uri, **config)
  File "/usr/lib64/python3.6/site-packages/neo4j/v1/direct.py", line 73, in __new__
    pool.release(pool.acquire())
  File "/usr/lib64/python3.6/site-packages/neo4j/v1/direct.py", line 44, in acquire
    return self.acquire_direct(self.address)
  File "/usr/lib64/python3.6/site-packages/neo4j/bolt/connection.py", line 453, in acquire_direct
    connection = self.connector(address, self.connection_error_handler)
  File "/usr/lib64/python3.6/site-packages/neo4j/v1/direct.py", line 70, in connector
    return connect(address, security_plan.ssl_context, error_handler, **config)
  File "/usr/lib64/python3.6/site-packages/neo4j/bolt/connection.py", line 707, in connect
    raise last_error
  File "/usr/lib64/python3.6/site-packages/neo4j/bolt/connection.py", line 698, in connect
    s, der_encoded_server_certificate = _secure(s, address[0], ssl_context, **config)
  File "/usr/lib64/python3.6/site-packages/neo4j/bolt/connection.py", line 601, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

**Comment by fabbione** [comment]
As a side note, also running some CLI commands generate tracebacks:

# simengine-cli
Traceback (most recent call last):
  File "/usr/bin/simengine-cli", line 11, in <module>
    from enginecore import cli
  File "/usr/share/simengine/enginecore/enginecore/cli/__init__.py", line 1, in <module>
    from enginecore.cli.status import status_command
  File "/usr/share/simengine/enginecore/enginecore/cli/status.py", line 8, in <module>
    from enginecore.state.api import IStateManager, ISystemEnvironment
  File "/usr/share/simengine/enginecore/enginecore/state/api/__init__.py", line 6, in <module>
    from enginecore.state.api.server import (
  File "/usr/share/simengine/enginecore/enginecore/state/api/server.py", line 9, in <module>
    import enginecore.model.system_modeler as sys_modeler
  File "/usr/share/simengine/enginecore/enginecore/model/system_modeler.py", line 16, in <module>
    GRAPH_REF = GraphReference()
  File "/usr/share/simengine/enginecore/enginecore/model/graph_reference.py", line 26, in __init__
    os.environ.get("NEO4J_PSW", "simengine"),
  File "/usr/lib64/python3.6/site-packages/neo4j/v1/api.py", line 94, in driver
    return Driver(uri, **config)
  File "/usr/lib64/python3.6/site-packages/neo4j/v1/api.py", line 133, in __new__
    return subclass(uri, **config)
  File "/usr/lib64/python3.6/site-packages/neo4j/v1/direct.py", line 73, in __new__
    pool.release(pool.acquire())
  File "/usr/lib64/python3.6/site-packages/neo4j/v1/direct.py", line 44, in acquire
    return self.acquire_direct(self.address)
  File "/usr/lib64/python3.6/site-packages/neo4j/bolt/connection.py", line 453, in acquire_direct
    connection = self.connector(address, self.connection_error_handler)
  File "/usr/lib64/python3.6/site-packages/neo4j/v1/direct.py", line 70, in connector
    return connect(address, security_plan.ssl_context, error_handler, **config)
  File "/usr/lib64/python3.6/site-packages/neo4j/bolt/connection.py", line 707, in connect
    raise last_error
  File "/usr/lib64/python3.6/site-packages/neo4j/bolt/connection.py", line 698, in connect
    s, der_encoded_server_certificate = _secure(s, address[0], ssl_context, **config)
  File "/usr/lib64/python3.6/site-packages/neo4j/bolt/connection.py", line 601, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
