### ISSUE TITLE
Simegine fails to build after npm module update on Centos 8

### ISSUE THREAD

**Issue by fabbione** [Seneca-CDOT/simengine#161]
+ npm run build

> simengine@1.0.0 build /root/rpmbuild/BUILD/simengine-dashboard-3.38/simengine-3.38/dashboard/frontend
> vite build

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/rpmbuild/BUILD/simengine-dashboard-3.38/simengine-3.38/dashboard/frontend/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:26:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simengine@1.0.0 build: `vite build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simengine@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-25T16_08_09_285Z-debug.log
error: Bad exit status from /var/tmp/rpm-tmp.G4xpjJ (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.G4xpjJ (%build)
buildall: Build of simengine-dashboard.spec failed

**Comment by fabbione** [comment]
According to https://github.com/Seneca-CDOT/simengine/pull/159, nodejs 12 or higher is required to build. In this case the rpm dependency needs to be changed:

nodejs is using epoch (1:...) and 1:10 is higher than 12 (0:12).

diff --git a/rpm/specfiles/simengine-dashboard.spec b/rpm/specfiles/simengine-dashboard.spec
index 678ef2a..f47e1db 100644
--- a/rpm/specfiles/simengine-dashboard.spec
+++ b/rpm/specfiles/simengine-dashboard.spec
@@ -9,7 +9,7 @@ License:   GPLv3+

 Source0:   https://github.com/Seneca-CDOT/simengine/archive/%{gittag}/simengine-%{version}.tar.gz

-BuildRequires: nodejs-devel >= 12
+BuildRequires: nodejs-devel >= 1:12
